#!/usr/bin/env bash
# Self-extracting copy of skyrl-test/anyscale-pr2198/. Paste into a terminal opened at the SkyRL
# repo root (or save as bundle.sh there and run `bash bundle.sh`). Generated by make_bundle.py.
set -euo pipefail
[[ -f examples/train/gsm8k/run_gsm8k.sh ]] || { echo "run this from the SkyRL repo root"; exit 1; }
mkdir -p skyrl-test/anyscale-pr2198
cat > skyrl-test/anyscale-pr2198/00_env.sh <<'PR2198_EOF'
# Source this on the Anyscale workspace, from the SkyRL checkout:
#   source skyrl-test/anyscale-pr2198/00_env.sh
# Mirrors the env_vars block of SkyRL/ci/anyscale_gpu_e2e_test.yaml. Never prints the key.
# Set WANDB_API_KEY first: Workspace > Dependencies > Environment variables (cluster-wide), or
# `export WANDB_API_KEY=...` in this shell -- SkyRL forwards it into the Ray runtime env itself
# (skyrl/train/utils/utils.py, prepare_runtime_environment), so the driver shell is enough.

: "${WANDB_API_KEY:?export WANDB_API_KEY first (see the comment at the top of this file)}"

# Every ci/anyscale_*.yaml sets this so SkyRL's own ray.init(runtime_env=...) wins over the
# job-level runtime env Anyscale installs. Assumed to matter for workspaces the same way.
export RAY_OVERRIDE_JOB_RUNTIME_ENV=1
# The install doc's "configure Ray to use uv" line: Ray workers get the same uv environment the
# driver runs in. Harmless if the image already sets it.
export RAY_RUNTIME_ENV_HOOK=ray._private.runtime_env.uv_runtime_env_hook.hook

# Single-node workspace (head = g6.12xlarge, 4xL4): $HOME is visible to every Ray worker.
# If the head node has no GPUs, point this at shared storage instead, e.g. /mnt/cluster_storage/data.
export PR2198_DATA="${PR2198_DATA:-$HOME/data}"
export PR2198_PROJECT="${PR2198_PROJECT:-pr2198_smoke}"

echo "branch : $(git rev-parse --abbrev-ref HEAD) @ $(git rev-parse --short HEAD)"
echo "uv     : $(uv --version 2>/dev/null || echo MISSING)"
echo "gpus   :"; nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>/dev/null || echo "  nvidia-smi failed"
echo "wandb  : key set (${#WANDB_API_KEY} chars)"
echo "data   : $PR2198_DATA   project: $PR2198_PROJECT"
PR2198_EOF
cat > skyrl-test/anyscale-pr2198/01_prepare_data.sh <<'PR2198_EOF'
#!/usr/bin/env bash
# Data for both smoke runs. Run from the SkyRL checkout on the workspace, after 00_env.sh.
#   bash skyrl-test/anyscale-pr2198/01_prepare_data.sh              # gsm8k + SQL prompts + sliced eval sets
#   WITH_SQL_DB=1 bash skyrl-test/anyscale-pr2198/01_prepare_data.sh # + the OmniSQL databases (22 GB zip, ~50 GB unzipped)
set -euo pipefail
DATA="${PR2198_DATA:-$HOME/data}"
HERE="$(cd "$(dirname "$0")" && pwd)"
SQL_EVAL_ROWS="${SQL_EVAL_ROWS:-32}"
GSM8K_EVAL_ROWS="${GSM8K_EVAL_ROWS:-256}"

hf_dl() { if command -v hf >/dev/null 2>&1; then hf "$@"; else uv run hf "$@"; fi; }

# gsm8k: 7473 train / 1319 validation rows, exactly as ci/gpu_e2e_test_run.sh prepares it.
uv run examples/train/gsm8k/gsm8k_dataset.py --output_dir "$DATA/gsm8k"

# SkyRL-SQL-653 prompts: 4.2 MB train, 0.6 MB validation (1034 Spider rows). Sizes fetched 2026-09-14.
hf_dl download NovaSky-AI/SkyRL-SQL-653-data-newfmt --local-dir "$DATA/sql" --repo-type dataset

# Smoke-sized eval sets. On the full sets the four evals would be the long pole of each run.
uv run "$HERE/slice_parquet.py" "$DATA/gsm8k/validation.parquet" "$DATA/gsm8k/validation_smoke.parquet" --rows "$GSM8K_EVAL_ROWS"
uv run "$HERE/slice_parquet.py" "$DATA/sql/validation.parquet" "$DATA/sql/validation_smoke.parquet" --rows "$SQL_EVAL_ROWS"

if [[ "${WITH_SQL_DB:-0}" == "1" ]]; then
  # The text2sql env executes generated SQL against these; every SQL eval/train row needs them.
  # Charlie's script expects DB_PATH=$HOME/data/sql/db_files/data, so unzip into db_files/ (the
  # zip's root being data/ is ASSUMED from that default -- the ls below is the check).
  mkdir -p "$DATA/sql/db_files"
  hf_dl download seeklhy/OmniSQL-datasets data.zip --repo-type dataset --local-dir "$DATA/sql/db_files"
  (cd "$DATA/sql/db_files" && unzip -q data.zip && rm -f data.zip)
  echo "DB root should be $DATA/sql/db_files/data:"; ls "$DATA/sql/db_files/data" | head
fi
echo "done: $DATA"
PR2198_EOF
cat > skyrl-test/anyscale-pr2198/02_run_sql_stepwise.sh <<'PR2198_EOF'
#!/usr/bin/env bash
# Run A: Charlie's step-wise SQL script, cut to a 3-step smoke run on 4xL4.
#   bash skyrl-test/anyscale-pr2198/02_run_sql_stepwise.sh
#   MODEL=Qwen/Qwen3-1.7B bash skyrl-test/anyscale-pr2198/02_run_sql_stepwise.sh   # if Qwen3-4B OOMs
# Every line below re-sets a key the script already passes. OmegaConf.from_cli applies overrides in
# order, last wins -- CI's tests/train/gpu_e2e_test/gsm8k_colocate.sh relies on exactly this.
set -euo pipefail
DATA="${PR2198_DATA:-$HOME/data}"
MODEL="${MODEL:-Qwen/Qwen3-4B}"
RUN_NAME="sql_stepwise_$(date +%Y%m%d%H%M%S)"
echo "$RUN_NAME" > /tmp/pr2198_last_sql_run
echo "run_name=$RUN_NAME  model=$MODEL  data=$DATA"

bash examples/train/step_wise/run_skyrl_sql_step_wise_qwen3.sh \
  trainer.policy.model.path="$MODEL" \
  data.train_data="['$DATA/sql/train.parquet']" \
  data.val_data="['$DATA/sql/validation_smoke.parquet']" \
  environment.skyrl_gym.text2sql.db_path="$DATA/sql/db_files/data" \
  trainer.placement.policy_num_gpus_per_node=4 \
  trainer.placement.ref_num_gpus_per_node=4 \
  generator.inference_engine.num_engines=2 \
  generator.inference_engine.tensor_parallel_size=2 \
  trainer.max_training_steps=3 \
  trainer.eval_before_train=true \
  trainer.eval_interval=1 \
  trainer.eval_batch_size=16 \
  generator.eval_n_samples_per_prompt=2 \
  trainer.num_logger_eval_samples=4 \
  trainer.train_batch_size=16 \
  trainer.policy_mini_batch_size=16 \
  generator.n_samples_per_prompt=2 \
  trainer.ckpt_interval=0 \
  trainer.hf_save_interval=-1 \
  trainer.dump_data_batch=false \
  trainer.project_name="${PR2198_PROJECT:-pr2198_smoke}" \
  trainer.run_name="$RUN_NAME" \
  trainer.ckpt_path="$HOME/ckpts/pr2198_sql_smoke" \
  "$@"
PR2198_EOF
cat > skyrl-test/anyscale-pr2198/03_run_gsm8k.sh <<'PR2198_EOF'
#!/usr/bin/env bash
# Run B: non-step-wise smoke run. examples/train/gsm8k/run_gsm8k.sh is the config CI runs on l4_ci
# (Qwen2.5-1.5B-Instruct, 4 GPUs); the micro batch sizes are CI's L4 values.
#   bash skyrl-test/anyscale-pr2198/03_run_gsm8k.sh
set -euo pipefail
DATA="${PR2198_DATA:-$HOME/data}"
RUN_NAME="gsm8k_$(date +%Y%m%d%H%M%S)"
echo "$RUN_NAME" > /tmp/pr2198_last_gsm8k_run
echo "run_name=$RUN_NAME  data=$DATA"

NUM_GPUS=4 DATA_DIR="$DATA/gsm8k" bash examples/train/gsm8k/run_gsm8k.sh \
  data.val_data="['$DATA/gsm8k/validation_smoke.parquet']" \
  trainer.max_training_steps=3 \
  trainer.eval_before_train=true \
  trainer.eval_interval=1 \
  trainer.eval_batch_size=128 \
  generator.eval_n_samples_per_prompt=2 \
  trainer.num_logger_eval_samples=4 \
  trainer.train_batch_size=256 \
  trainer.policy_mini_batch_size=256 \
  trainer.micro_forward_batch_size_per_gpu=16 \
  trainer.micro_train_batch_size_per_gpu=16 \
  trainer.ckpt_interval=0 \
  trainer.project_name="${PR2198_PROJECT:-pr2198_smoke}" \
  trainer.run_name="$RUN_NAME" \
  trainer.ckpt_path="$HOME/ckpts/pr2198_gsm8k_smoke" \
  "$@"
PR2198_EOF
cat > skyrl-test/anyscale-pr2198/slice_parquet.py <<'PR2198_EOF'
"""Keep the first N rows of a parquet file, schema untouched: a smoke-sized eval set.

    uv run skyrl-test/anyscale-pr2198/slice_parquet.py SRC.parquet DST.parquet --rows 32
"""

import argparse

import pyarrow.parquet as pq

ap = argparse.ArgumentParser()
ap.add_argument("src")
ap.add_argument("dst")
ap.add_argument("--rows", type=int, default=32)
a = ap.parse_args()

table = pq.read_table(a.src)
n = min(a.rows, table.num_rows)
pq.write_table(table.slice(0, n), a.dst)
print(f"{a.dst}: {n} of {table.num_rows} rows")
PR2198_EOF
cat > skyrl-test/anyscale-pr2198/check_code_path.py <<'PR2198_EOF'
"""Prove which `skyrl` the driver AND a Ray worker import: this checkout (the PR branch) or a copy
baked into the image. Run from the SkyRL repo root, after 00_env.sh:

    uv run --isolated --extra fsdp skyrl-test/anyscale-pr2198/check_code_path.py

Both lines must show this checkout's path, the branch's commit, and dispatcher=True (the module
skyrl.train.eval.dispatcher exists only on PR 2198). A worker line pointing into site-packages, or
dispatcher=False, means Ray workers are not running in the driver's uv environment: check that
RAY_RUNTIME_ENV_HOOK is exported (00_env.sh does it) and that you ran from the repo root.
"""

import importlib.util
import os
import subprocess
import sys


def describe():
    import skyrl  # noqa: F401  -- resolved inside whichever process runs this

    repo = os.path.dirname(os.path.dirname(skyrl.__file__))
    try:
        commit = subprocess.check_output(["git", "-C", repo, "rev-parse", "--short", "HEAD"], text=True).strip()
    except Exception:  # no .git next to an installed copy
        commit = "no-git"
    return {
        "skyrl": skyrl.__file__,
        "commit": commit,
        "dispatcher": importlib.util.find_spec("skyrl.train.eval.dispatcher") is not None,
        "python": sys.executable,
    }


def fmt(d):
    return f"{d['skyrl']}  commit={d['commit']}  dispatcher={d['dispatcher']}  python={d['python']}"


print("driver:", fmt(describe()))

import ray  # noqa: E402

ray.init(logging_level="ERROR")
print("worker:", fmt(ray.get(ray.remote(describe).remote())))
PR2198_EOF
cat > skyrl-test/anyscale-pr2198/check_wandb_run.py <<'PR2198_EOF'
"""Verify PR 2198's W&B layout on a finished smoke run, from the run's full history.

    uv run --isolated --extra fsdp skyrl-test/anyscale-pr2198/check_wandb_run.py \
        --project pr2198_smoke --run_name "$(cat /tmp/pr2198_last_gsm8k_run)" \
        --expect_key eval/all/pass_at_2

Checks:
  1. every row carries `global_step` (the adapter injects it; `_step` is only a call counter);
  2. eval rows (any `eval/*` key) sit exactly at --expect_eval_steps, each with `eval/all/avg_score`;
  3. `timing/eval_generate` and every --expect_key are on every eval row;
  4. eval keys never share a row with training keys (they left the per-step payload);
  5. the summary still exposes `eval/all/avg_score` (tests/train/gpu_e2e_test/get_summary.py compatibility);
  6. reports the W&B tables logged (the eval trajectory table goes through the new log_table path).
"""

import argparse
import sys

import wandb

ap = argparse.ArgumentParser()
ap.add_argument("--project", required=True)
ap.add_argument("--run_name", required=True)
ap.add_argument("--entity", default=None, help="defaults to the API key's entity, as get_summary.py does")
ap.add_argument("--expect_eval_steps", default="0,1,2,3")
ap.add_argument("--expect_key", action="append", default=[], help="a key every eval row must have; repeatable")
a = ap.parse_args()

api = wandb.Api()
path = f"{a.entity}/{a.project}" if a.entity else a.project
run = next(iter(api.runs(path, filters={"display_name": a.run_name}, order="-created_at")), None)
if run is None:
    sys.exit(f"run {a.run_name!r} not found in {path}")
rows = list(run.scan_history())
failures = []


def check(cond, msg):
    print(("ok    " if cond else "FAIL  ") + msg)
    if not cond:
        failures.append(msg)


check(all("global_step" in r for r in rows), f"all {len(rows)} rows carry global_step")
steps = [r["_step"] for r in rows if "_step" in r]
check(len(set(steps)) == len(steps), "_step is unique per row (a call counter, one row per log call)")

eval_rows = [r for r in rows if any(k.startswith("eval/") for k in r)]
expected = sorted(int(s) for s in a.expect_eval_steps.split(","))
got = sorted({int(r["global_step"]) for r in eval_rows if "global_step" in r})
check(got == expected, f"eval rows at global_step {got} (expected {expected})")
check(bool(eval_rows) and all("eval/all/avg_score" in r for r in eval_rows), "every eval row has eval/all/avg_score")
for key in ["timing/eval_generate", *a.expect_key]:
    check(bool(eval_rows) and all(key in r for r in eval_rows), f"every eval row has {key}")

TRAIN_PREFIXES = ("trainer/", "loss/", "policy/", "critic/", "generate/", "vllm/")
check(
    all(not [k for k in r if k.startswith(TRAIN_PREFIXES)] for r in eval_rows),
    "eval keys never share a row with training keys",
)
check("eval/all/avg_score" in run.summary, "summary exposes eval/all/avg_score (get_summary.py still works)")

tables = sorted({k for r in rows for k, v in r.items() if isinstance(v, dict) and v.get("_type") == "table-file"})
print(f"info  tables logged: {tables or 'none'}")
if eval_rows:
    print("info  keys on the first eval row: " + ", ".join(sorted(k for k in eval_rows[0] if not k.startswith("_"))))
    print("\nstep  avg_score" + "".join(f"  {k}" for k in a.expect_key))
    for r in sorted(eval_rows, key=lambda r: r["global_step"]):
        extras = "".join(f"  {r.get(k, float('nan')):.4f}" for k in a.expect_key)
        print(f"{int(r['global_step']):>4}  {r['eval/all/avg_score']:.4f}{extras}")

sys.exit(1 if failures else 0)
PR2198_EOF
chmod +x skyrl-test/anyscale-pr2198/*.sh
echo "wrote:"; ls -la skyrl-test/anyscale-pr2198
