"""Regenerate bundle.sh: one paste on the workspace recreates every file in this folder.

    python skyrl-test/anyscale-pr2198/make_bundle.py
"""

from pathlib import Path

HERE = Path(__file__).resolve().parent
FILES = [
    "00_env.sh",
    "01_prepare_data.sh",
    "02_run_sql_stepwise.sh",
    "03_run_gsm8k.sh",
    "slice_parquet.py",
    "check_code_path.py",
    "check_wandb_run.py",
]
DELIM = "PR2198_EOF"

parts = [
    "#!/usr/bin/env bash",
    "# Self-extracting copy of skyrl-test/anyscale-pr2198/. Paste into a terminal opened at the SkyRL",
    "# repo root (or save as bundle.sh there and run `bash bundle.sh`). Generated by make_bundle.py.",
    "set -euo pipefail",
    '[[ -f examples/train/gsm8k/run_gsm8k.sh ]] || { echo "run this from the SkyRL repo root"; exit 1; }',
    "mkdir -p skyrl-test/anyscale-pr2198",
]
for name in FILES:
    body = (HERE / name).read_text()
    assert DELIM not in body, name
    parts += [f"cat > skyrl-test/anyscale-pr2198/{name} <<'{DELIM}'", body.rstrip("\n"), DELIM]
parts += ["chmod +x skyrl-test/anyscale-pr2198/*.sh", 'echo "wrote:"; ls -la skyrl-test/anyscale-pr2198']
(HERE / "bundle.sh").write_text("\n".join(parts) + "\n")
print(f"bundle.sh: {len(FILES)} files, {sum(1 for _ in (HERE / 'bundle.sh').open())} lines")
